name: langchain_rag_env
dependencies:
  - python=3.8
  - pip
  - pip:
      - packaging==24.2
      - langchain-openai==0.1.25
      - langchain-community==0.2.18
      - packaging==20.0
      - dask==2022.10.2
      - faiss-cpu==1.8.0.post1
      - marshmallow==3.22.0
      - matplotlib==3.5.3
      - rasa==3.6.20
      - openai==1.54.1
      - python-dotenv==1.0.1
      - chardet==5.2.0
      - numpy==1.23.5
      - pandas==2.0.3
      - scikit-learn==1.1.3
      - joblib==1.2.0
      - openpyxl==3.1.5
      - fsspec==2024.6.0

  # Additional dependencies for Rasa
  - libffi
  - openssl
  - make
  - libgcc
  - gxx_linux-64
  - pip
  - wheel

prefix: ./envs/langchain_rag_env

#conda env create -f environment.yml

#conda activate langchain_rag_env

