name: rasa-chatbot
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.9.24
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - aio-pika==8.2.3
    - aiofiles==24.1.0
    - aiogram==2.15
    - aiohttp-retry==2.8.3
    - aiormq==6.4.2
    - altair==5.4.1
    - anyio==4.5.2
    - apscheduler==3.9.1.post1
    - astunparse==1.6.3
    - attrs==22.1.0
    - babel==2.16.0
    - backoff==2.2.1
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.12.3
    - bidict==0.23.1
    - blinker==1.8.2
    - boto3==1.35.39
    - botocore==1.35.39
    - cachecontrol==0.12.14
    - cachetools==5.5.0
    - certifi==2024.8.30
    - cffi==1.17.1
    - chardet==5.2.0
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpickle==2.2.1
    - colorclass==2.2.2
    - coloredlogs==15.0.1
    - colorhash==1.2.1
    - confluent-kafka==2.6.0
    - cryptography==43.0.3
    - cycler==0.12.1
    - cython==3.0.11
    - dask==2022.10.2
    - dnspython==2.3.0
    - docopt==0.6.2
    - duckdb==1.1.2
    - duckdb-engine==0.13.4
    - emoji==2.14.0
    - et-xmlfile==2.0.0
    - eval-type-backport==0.2.0
    - exceptiongroup==1.2.2
    - faiss-cpu==1.8.0.post1
    - fbmessenger==6.0.0
    - filetype==1.2.0
    - fire==0.7.0
    - flatbuffers==24.3.25
    - fonttools==4.54.1
    - future==1.0.0
    - gast==0.4.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.35.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - grpcio==1.66.2
    - h11==0.14.0
    - h5py==3.11.0
    - httpcore==1.0.6
    - httptools==0.6.1
    - httpx==0.27.2
    - humanfriendly==10.0
    - idna==3.10
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - jax==0.4.13
    - jinja2==3.1.4
    - jiter==0.7.0
    - jmespath==1.0.1
    - joblib==1.2.0
    - jsonpath-python==1.0.6
    - jsonpickle==3.0.4
    - jsonschema==4.17.3
    - keras==2.12.0
    - kiwisolver==1.4.7
    - langchain==0.2.17
    - langchain-community==0.2.17
    - langchain-core==0.2.43
    - langchain-openai==0.1.25
    - langchain-text-splitters==0.2.4
    - langdetect==1.0.9
    - langsmith==0.1.137
    - libclang==18.1.1
    - locket==1.0.0
    - lxml==5.3.0
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - matplotlib==3.5.3
    - mattermostwrapper==2.2
    - mdurl==0.1.2
    - ml-dtypes==0.2.0
    - msgpack==1.1.0
    - multidict==5.2.0
    - narwhals==1.11.1
    - nest-asyncio==1.6.0
    - networkx==2.6.3
    - numpy==1.23.5
    - oauthlib==3.2.2
    - openai==1.54.1
    - openpyxl==3.1.5
    - opt-einsum==3.4.0
    - packaging==20.9
    - pamqp==3.2.1
    - partd==1.4.1
    - pkgutil-resolve-name==1.3.10
    - pluggy==1.5.0
    - portalocker==2.10.1
    - prompt-toolkit==3.0.28
    - protobuf==4.23.3
    - psycopg2-binary==2.9.9
    - pyarrow==17.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pycparser==2.22
    - pydantic==1.10.9
    - pydantic-core==2.23.4
    - pydeck==0.9.1
    - pydot==1.4.2
    - pygments==2.18.0
    - pyjwt==2.9.0
    - pykwalify==1.8.0
    - pymongo==4.3.3
    - pyparsing==3.1.4
    - pyrsistent==0.20.0
    - python-crfsuite==0.9.11
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-engineio==4.10.0
    - python-iso639==2024.10.22
    - python-magic==0.4.27
    - python-socketio==5.11.4
    - pytz==2022.7.1
    - questionary==1.10.0
    - randomname==0.1.5
    - rapidfuzz==3.9.7
    - rasa==3.6.20
    - rasa-sdk==3.6.2
    - redis==4.6.0
    - regex==2022.10.31
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - requests-toolbelt==1.0.0
    - rich==13.9.3
    - rocketchat-api==1.30.0
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.8
    - s3transfer==0.10.3
    - sanic==21.12.2
    - sanic-cors==2.0.1
    - sanic-jwt==1.8.0
    - sanic-routing==0.7.2
    - scikit-learn==1.1.3
    - scipy==1.10.1
    - sentry-sdk==1.14.0
    - simple-websocket==1.1.0
    - six==1.16.0
    - sklearn-crfsuite==0.3.6
    - slack-sdk==3.33.1
    - smmap==5.0.1
    - sniffio==1.3.1
    - soupsieve==2.6
    - sqlalchemy==1.4.54
    - streamlit==1.39.0
    - structlog==23.3.0
    - structlog-sentry==2.1.0
    - tabulate==0.9.0
    - tarsafe==0.0.4
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.2
    - tensorflow==2.12.0
    - tensorflow-estimator==2.12.0
    - tensorflow-hub==0.13.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - tensorflow-text==2.12.0
    - termcolor==2.4.0
    - terminaltables==3.1.10
    - threadpoolctl==3.5.0
    - toml==0.10.2
    - toolz==1.0.0
    - tornado==6.4.1
    - twilio==8.2.2
    - typing-extensions==4.12.2
    - typing-utils==0.1.0
    - tzlocal==5.2
    - ujson==5.10.0
    - unstructured==0.11.8
    - unstructured-client==0.27.0
    - urllib3==1.26.20
    - uvloop==0.20.0
    - watchdog==4.0.2
    - wcwidth==0.2.13
    - webexteamssdk==1.6.1
    - websockets==10.4
    - werkzeug==3.0.4
    - wrapt==1.14.1
    - wsproto==1.2.0
    - zipp==3.20.2
prefix: /home/ganesh/anaconda3/envs/rasa-chatbot
